
#内置的tomcat服务启动监听端口号
server:
  port: 10086
#应用名称
spring:
  application:
    name: EurekaServer
#EurekaServer配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka #指向高可用另外一台Eureka服务器
